### ISSUE TITLE
(feat) localhost 

### ISSUE THREAD

**Issue by lukasmrtvy** [TelkomIndonesia/terraform-provider-linux#10]
Is possible to run this on localhost without using ssh ? I want to run this provider in CI, in container..
```
provider "linux" {
   local = true
}
```
Thanks

**Comment by rucciva** [comment]
Hi, i don't think it is supported yet. But if you want to use the linux_script resource, then i think it is better to use this provider https://github.com/scottwinkler/terraform-provider-shell

**Comment by rucciva** [comment]
Closing this, feel free to reopen if the above comment don't solve the problem.
